### ISSUE TITLE
Create first homework

### ISSUE THREAD

**Issue by rustymuffin99** [rustymuffin99/119-repository#2]

**Comment by ryarza** [comment]
Hi @rustymuffin99,

The pull request you made from first-homework to main should be linked to this issue. Once the request is linked, you can accept the pull request, which will close this issue. See for reference: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Once you do that, please tag me again in the "create first homework" issue.

**Comment by rustymuffin99** [comment]
@ryarza I think I fixed it and I linked it to this create first homework. Thanks for the help!

**Comment by ryarza** [comment]
Hi @rustymuffin99,

Yes, I see the pull request is linked to this issue. Can you accept the pull request? Doing so will merge the first-homework branch into the main branch, and will automatically close this issue. Please tag me again once you do that.
